### ISSUE TITLE
API Console page does not follow the new dark-theme style.

### ISSUE THREAD

**Issue by ixuz** [MagnumOpuses/jobtechdev.se#10]
API Console page does not follow the new dark-theme style.

Please see page: https://jobtechdev.se/doc/api/dev_guide/apiconsole/

**Comment by perui** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [c](https://trello.com/c/fQ8NHG15/216-c)

**Comment by ixuz** [comment]
Fixed in: https://github.com/MagnumOpuses/jobtechdev.se/pull/23
