### ISSUE TITLE
Lefthand nav menu gradually slides into view

### ISSUE THREAD

**Issue by ixuz** [MagnumOpuses/jobtechdev.se#19]
**Describe the bug**
The lefthand navigation menu gradually slides/interpolates into view on every page load.

**To Reproduce**
1. Visit any documentation page with Internet Explorer 11.

**Expected behavior**
The lefthand nav menu should not move/animate, it should immediately be shown at its correct destination (this works fine in Chrome and Firefox).

**Screenshots**
![menu-slides-1](https://user-images.githubusercontent.com/7243912/59750895-d85d3600-927f-11e9-858c-baa107c5bd37.png)
![menu-slides-2](https://user-images.githubusercontent.com/7243912/59750902-db582680-927f-11e9-8260-1b944432ecbb.png)
![menu-slides-3](https://user-images.githubusercontent.com/7243912/59750909-dd21ea00-927f-11e9-8637-ae0649910dbd.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser IE 11.765.17134.0
 - Version N/A

**Additional context**
N/A

**Comment by markella-n-th** [comment]
Fix merged to develop, will be available on stage and production soon.
