### ISSUE TITLE
Lisens

### ISSUE THREAD

**Issue by halge** [MagnumOpuses/jobtechdev.se#205]
https://jobtechdev.se/en/docs/devguide/licens/
change menu Lisens to License. But it is better to use British with "c".

**Comment by halge** [comment]
Refused to load the image 'https://widgets.jobtechdev.se/alljobads/example/demo.jpg' because it violates the following Content Security Policy directive: "img-src 'self' blob: stats.g.doubleclick.net online.swagger.io *.gstatic.com raw.githubusercontent.com gitlab.com github.com data:".

https://jobtechdev.se/en/docs/projects/af_connect/
Solution: add path to nginx CSP.

**Comment by halge** [comment]
https://jobtechdev.se/en/docs/projects/joblinks/
404 on https://jobtechdev.se/en/docs/projects/joblinks/uploads/65f81c80eb5626900a7f0d5cfab0ba70/image.png

**Comment by halge** [comment]
https://jobtechdev.se/en/docs/projects/jobscanner/
404 on jobtech link

**Comment by perui** [comment]
> https://jobtechdev.se/en/docs/projects/jobscanner/
> 404 on jobtech link

Fixexd

**Comment by perui** [comment]
> https://jobtechdev.se/en/docs/projects/joblinks/
> 404 on https://jobtechdev.se/en/docs/projects/joblinks/uploads/65f81c80eb5626900a7f0d5cfab0ba70/image.png
> and all pdfs

depends on the way the documentation is written. I have contacted the owner of the documentation.

**Comment by halge** [comment]
> > https://jobtechdev.se/en/docs/projects/joblinks/
> > 404 on https://jobtechdev.se/en/docs/projects/joblinks/uploads/65f81c80eb5626900a7f0d5cfab0ba70/image.png
> > and all pdfs
> 
> depends on the way the documentation is written. I have contacted the owner of the documentation.

put it to separate issue, sorry for the mess)
