### ISSUE TITLE
Two swagger UI images fail to load due to Content Security Policy restriction.

### ISSUE THREAD

**Issue by ixuz** [MagnumOpuses/jobtechdev.se#26]
**Describe the bug**
At the bottom of the API Console page there's a small broken image icon with a visible label "Error".

It's caused by the Content Security Policy not accepting resources from online.swagger.io.

**To Reproduce 1**
1. Visit Production site, api console: https://jobtechdev.se/api/dev_guide/apiconsole/
2. Scroll down to bottom
3. See a "broken image"-icon with text label "Error"

**To Reproduce 2**
1. Visit Stage site, api console: https://stage.jobtechdev.se/api/dev_guide/apiconsole/ (requires authentication)
2. Scroll down to bottom
3. See a "broken image"-icon with text label "Error"

**Expected behavior**
No visible swagger errors on page/console.

**Screenshots**

![chrome_2019-06-22_00-28-33](https://user-images.githubusercontent.com/7243912/59954396-b54fa380-9484-11e9-8059-5f9561c909dd.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**

```
Refused to load the image 'https://online.swagger.io/validator?url=https%3A%2F%2Fjobtechdev.se%2Fapi%2Fdev_guide%2Fapiconsole%2F' because it violates the following Content Security Policy directive: "img-src 'self' *.googletagmanager.com *.google-analytics.com stats.g.doubleclick.net".
```
```
Refused to load the image 'https://online.swagger.io/validator?url=https%3A%2F%2Fjobtechdev.se%2Fontology%2Fswagger.json' because it violates the following Content Security Policy directive: "img-src 'self' *.googletagmanager.com *.google-analytics.com stats.g.doubleclick.net".
```

**Comment by markella-n-th** [comment]
Fix merged to develop, will be available on stage and production soon.
