### ISSUE TITLE
Typo "Öpen källkod" in Swedish top navigation bar (front page)

### ISSUE THREAD

**Issue by ixuz** [MagnumOpuses/jobtechdev.se#27]
**Describe the bug**
Small typo/mistake in the Swedish top navigation bar at the front page.

**To Reproduce**
1. Go to https://jobtechdev.se/sv/
4. See typo in top navigation bar "Öpen källkod"

**Expected behavior**
The label should be **"Öppen källkod"** instead of "Öpen källkod".

**Screenshots**
![chrome_2019-06-23_23-31-01](https://user-images.githubusercontent.com/7243912/59982213-04294480-960f-11e9-94de-816a72dded04.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
N/A

**Comment by markella-n-th** [comment]
Fix merged and will be available in stage and develop soon.
