### ISSUE TITLE
JQuery throws exception "revapi1077 is not defined"

### ISSUE THREAD

**Issue by ixuz** [MagnumOpuses/jobtechdev.se#28]
**Describe the bug**
When visiting the front page an error is thrown by jquery that "revapi is not defined".

**To Reproduce**
1. Go to https://jobtechdev.se/
2. Open Developer Tools, tab "Console"
3. See error "revapi1077 is not defined"

**Expected behavior**
Expecting no jquery/revapi errors in the console.

**Screenshots**
![chrome_2019-06-24_00-13-16](https://user-images.githubusercontent.com/7243912/59982586-e7900b00-9614-11e9-9181-371826121426.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
N/A

**Comment by markella-n-th** [comment]
Fix merged to develop, will be available on stage and production soon.
