### ISSUE TITLE
Uncaught exception "sticky is not a function" on documentation pages

### ISSUE THREAD

**Issue by ixuz** [MagnumOpuses/jobtechdev.se#29]
**Describe the bug**
Visiting any documentation page throws an uncaught exception error: `sticky is not a function`.

**To Reproduce**
1. Go to https://jobtechdev.se/about/ *(or any other documentation page)*
2. Open Developer Tools, tab "Console"
3. See error `Uncaught SyntaxError: Unexpected token ,`
4. See error `Uncaught TypeError: $(...).sticky is not a function`

**Expected behavior**
Expecting no jquery sticky errors in the console.

**Screenshots**
![chrome_2019-06-24_00-19-00](https://user-images.githubusercontent.com/7243912/59982630-b6fca100-9615-11e9-97b2-67fad4f164f4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
N/A

**Comment by markella-n-th** [comment]
Fix merged and will be available in stage and develop soon.
