### ISSUE TITLE
Shortcode "notices" fails to render on Hugo version 0.55+

### ISSUE THREAD

**Issue by ixuz** [MagnumOpuses/jobtechdev.se#30]
**Describe the bug**
The `{{% notice info %}}` shortcode from _hugo-theme-learn_ fails to render when running site with hugo version 0.55 or greater.

This is caused due to Hugo v0.55 changed under which circumstances the **.Inner** shortcode is wrapped with paragraph `<p>` tags.

Further details about this can be found here:
- https://github.com/matcornic/hugo-theme-learn/issues/272

**To Reproduce**
1. Acquire Hugo version 0.55+.
2. Build and run the site `npm install` `npm run start`
3. Visit page http://localhost:3000/api/occupation/occupations/
4. See that the topmost *notice info* isn't rendered properly.

**Expected behavior**
Expecting the notices to render properly as shown in the **Screenshots** section.

**Screenshots**
Expected visual result:
![notice - expected](https://user-images.githubusercontent.com/7243912/60019913-35495980-968f-11e9-9011-9b799e5f5e11.png)

Actual visual result:
![notice - error](https://user-images.githubusercontent.com/7243912/60019929-3b3f3a80-968f-11e9-8af4-e51c0511ffc5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, IE11
 - Hugo version: v0.55.5-A83256B9 windows/amd64 BuildDate: 2019-05-02

**Additional context**
The docker image uses a very old version of Hugo v0.27 (BuildDate: 2017-09-11) and therefore this error is not present in docker deployments such as **stage** and **production** environment.

A good next step to resolve this issue is to upgrade Hugo to the most recent version and update this project accordingly.

**Comment by markella-n-th** [comment]
Fix merged and will be available in stage and develop soon.
