### ISSUE TITLE
Unable to open any PDF files in PDF JS viewer.

### ISSUE THREAD

**Issue by ixuz** [MagnumOpuses/jobtechdev.se#40]
**Describe the bug**
Unable to open any PDF files in PDF JS viewer.

**To Reproduce**
1. Go to https://jobtechdev.se/open_source/papers/
2. Click on 'View “Digital Frontrunners Web” (English) (2318 kb)'
4. See error in web console and notice that the PDF is not loaded in pdfjs viewer.

**Expected behavior**
Expecting to see the selected PDF directly in the web pdfjs viewer and no errors in web console.

**Screenshots**
![no-pdf-loads](https://user-images.githubusercontent.com/7243912/60241314-4bcffa80-98b3-11e9-9eb9-df561ecdd423.png)
![no-pdf-loads-console](https://user-images.githubusercontent.com/7243912/60241317-4ecaeb00-98b3-11e9-9a36-0eafc530d482.png)

**Laptop:**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
N/A

**Comment by markella-n-th** [comment]
Fix merged to develop, will be available on stage and production soon.
