### ISSUE TITLE
Website title incorrect

### ISSUE THREAD

**Issue by ixuz** [MagnumOpuses/jobtechdev.se#87]
**Describe the bug**
The Jobtechdev.se website's title is incorrect, it says "JobTech Developer", but I believe it should say "JobTech Development".

**To Reproduce**
1. Go to '[Jobtechdev.se](https://jobtechdev.se/)'
2. See the website's title is incorrect.

**Expected behavior**
The title should have the text "JobTech Development".

**Screenshots**
![jobtech-title-wrong](https://user-images.githubusercontent.com/7243912/64847796-23cd7900-d610-11e9-87cf-613ba95a1489.png)

**Laptop:**
 - OS: Windows 10
 - Browser Chrome
 - Version 74.0.3729.169

**Additional context**
N/A

**Comment by perui** [comment]
Fixat
